-- 2025. 08. 03

-- SOL_1
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO
    GROUP BY FOOD_TYPE)
order by FOOD_TYPE desc

-- SOL_2
select FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
from REST_INFO
where(FOOD_TYPE, FAVORITES) in (select FOOD_TYPE, max(FAVORITES)
                                from REST_INFO
                                group by FOOD_TYPE)
order by FOOD_TYPE desc